import os
import json
import hashlib
import logging
import google.generativeai as genai
from typing import Dict, Any

logger = logging.getLogger(__name__)

# Load the secret API key from our .env file
from dotenv import load_dotenv

load_dotenv()

api_key = os.getenv("GEMINI_API_KEY", "")
if api_key:
    genai.configure(api_key=api_key)

# We use the fast 'flash' model for quick responses
MODEL_NAME = "gemini-2.5-flash"

# Our local notebook to remember past SQL answers
# Format: {"hashed_question": "SELECT ..."}
_sql_cache = {}


# --- INSTRUCTIONS FOR THE INTERN (SYSTEM PROMPTS) ---

SQL_INSTRUCTIONS = """You are an expert database assistant.
Return ONLY the raw SQLite SQL query. No explanations, no markdown.
Only generate SELECT queries. Use the exact column names provided.
"""

INSIGHT_INSTRUCTIONS = """You are a helpful data analyst.
Look at the user's question and the data result.
Return exactly this JSON format, nothing else:
{
  "insight": "A plain English sentence explaining the result.",
  "follow_ups": ["Next question 1", "Next question 2", "Next question 3"]
}
"""

HEAL_INSTRUCTIONS = """You are a SQL debugger.
You will see a broken SQL query and the error it caused.
Return ONLY the fixed SQLite query. No explanations.
"""


# --- ACTIONS TO TALK TO THE INTERN ---


def _ask_gemini(instructions: str, prompt: str) -> str:
    """
    Sends a prompt and system instructions to the Gemini API and returns the generated text.

    Args:
        instructions (str): The system prompt detailing the persona and rules.
        prompt (str): The user input or specific task prompt.

    Returns:
        str: The generated text response from the LLM.
    """
    # This is our helper that actually sends the message over the internet
    model = genai.GenerativeModel(
        model_name=MODEL_NAME, system_instruction=instructions
    )
    response = model.generate_content(prompt)
    return response.text.strip()


def generate_sql(schema_text: str, question: str, history: list = None) -> str:
    """
    Generates a SQL query based on a provided database schema and a natural language question.
    Uses caching to avoid redundant LLM calls for identical queries.
    Accepts conversation history for multi-turn follow-up questions.

    Args:
        schema_text (str): The formatted database schema.
        question (str): The user's natural language question.
        history (list): Optional list of past {question, sql} dicts for context.

    Returns:
        str: The raw SQL query generated by the LLM.
    """
    # 1. Check if we already know the answer (Caching)
    fingerprint_text = f"{schema_text}||{question.lower()}"
    fingerprint = hashlib.sha256(fingerprint_text.encode()).hexdigest()

    if fingerprint in _sql_cache:
        return _sql_cache[fingerprint]

    # 2. Build the message for the intern
    # Include last 3 conversation turns if available
    history_text = ""
    if history:
        history_text = "\n\nCONVERSATION HISTORY (last 3 turns for context):\n"
        for turn in history[-3:]:
            history_text += f"  Q: {turn['question']}\n  SQL: {turn['sql']}\n\n"

    prompt = (
        f"DATABASE SCHEMA:\n{schema_text}"
        f"{history_text}"
        f"\n\nCURRENT QUESTION:\n{question}"
    )

    # 3. Ask the intern
    sql = _ask_gemini(SQL_INSTRUCTIONS, prompt)

    # 4. Write it in our notebook for next time
    _sql_cache[fingerprint] = sql
    return sql


def generate_insight(question: str, sql: str, data_result: str) -> Dict[str, Any]:
    """
    Generates a natural language insight and follow-up questions based on query results.

    Args:
        question (str): The original user question.
        sql (str): The SQL query that was executed.
        data_result (str): The stringified result of the SQL query.

    Returns:
        Dict[str, Any]: A dictionary containing 'insight' (str) and 'follow_ups' (List[str]).
    """
    prompt = f"QUESTION: {question}\nSQL: {sql}\nDATA:\n{data_result}"

    raw_answer = _ask_gemini(INSIGHT_INSTRUCTIONS, prompt)

    # The intern gave us text, we need to turn it back into a Python Dictionary
    try:
        # Use regex to safely strip ```json and ``` markers
        import re
        clean_json = re.sub(r"^```(?:json)?\s*", "", raw_answer.strip(), flags=re.IGNORECASE)
        clean_json = re.sub(r"\s*```$", "", clean_json.strip())
        return json.loads(clean_json)
    except Exception:
        return {"insight": raw_answer, "follow_ups": []}


def heal_sql(broken_sql: str, error_msg: str, schema_text: str) -> str:
    """
    Attempts to fix a broken SQL query using the exact error message and schema context.

    Args:
        broken_sql (str): The SQL query that caused the error.
        error_msg (str): The exact SQLite error message.
        schema_text (str): The formatted database schema.

    Returns:
        str: A corrected SQL query.
    """
    prompt = (
        f"SCHEMA:\n{schema_text}\n\nBROKEN SQL:\n{broken_sql}\n\nERROR:\n{error_msg}"
    )
    return _ask_gemini(HEAL_INSTRUCTIONS, prompt)
