import sqlite3
import pandas as pd
from typing import Dict
import logging

logger = logging.getLogger(__name__)


def get_schema(conn: sqlite3.Connection) -> Dict[str, Dict[str, str]]:
    """
    Extracts the database schema (tables and columns) from a SQLite connection.

    Args:
        conn (sqlite3.Connection): The SQLite database connection.

    Returns:
        Dict[str, Dict[str, str]]: A dictionary mapping table names to their columns and data types.
    """
    cursor = conn.cursor()

    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = [row[0] for row in cursor.fetchall()]

    schema = {}
    for table in tables:
        cursor.execute(f"PRAGMA table_info({table});")
        columns = {}
        for row in cursor.fetchall():
            col_name = row[1]
            col_type = row[2]
            columns[col_name] = col_type
        schema[table] = columns

    return schema


def schema_to_string(schema: Dict[str, Dict[str, str]]) -> str:
    """
    Formats the schema dictionary into a readable string format for the LLM prompt.

    Args:
        schema (Dict[str, Dict[str, str]]): The schema dictionary generated by get_schema.

    Returns:
        str: A formatted string representation of the schema.
    """
    lines = []

    for table, columns in schema.items():
        lines.append(f"Table: {table}")
        for col_name, col_type in columns.items():
            lines.append(f"  - {col_name} ({col_type})")
        lines.append("")

    return "\n".join(lines).strip()


def get_sample_rows(conn: sqlite3.Connection, table: str, n: int = 3) -> str:
    """
    Retrieves a sample of rows from a specific table to provide data context.

    Args:
        conn (sqlite3.Connection): The SQLite database connection.
        table (str): The name of the table to sample from.
        n (int, optional): The number of rows to sample. Defaults to 3.

    Returns:
        str: A markdown-formatted string of the sampled rows, or an empty string on failure.
    """
    try:
        df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT {n}", conn)
        return df.to_markdown(index=False)
    except Exception:
        return ""
